DEBIAN := "debian:bookworm"
ALPINE := "alpine:3.20"
REPO := "SrzStephen/devcontainer-features"

default: all

all: lint test

lint:
	find src -name "*.sh" | xargs shellcheck
	npx --yes prettier@3.8.3 --check "**/*.{json,yaml,yml,md}"

test: test-claude-code test-just test-kiro-cli test-nvidia-container-toolkit test-act test-gitlab-ci-local test-prek test-bash-language-server test-gitlab-cli test-terraform-ls test-agentcore test-aws-sam-cli

setup-qemu:
	docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

_check-qemu:
	@docker run --rm --platform linux/arm64 alpine:3.20 true 2>/dev/null || \
		(echo "arm64 emulation not available — run 'just setup-qemu' first" && exit 1)

# Runs autogenerated (test.sh) tests only — scenario tests (scenarios.json) are covered by CI arm64 runners.
# Prerequisite: run 'just setup-qemu' once after each container restart.
test-arm64: _check-qemu test-claude-code-arm64 test-just-arm64 test-kiro-cli-arm64 test-nvidia-container-toolkit-arm64 test-act-arm64 test-gitlab-ci-local-arm64 test-prek-arm64 test-bash-language-server-arm64 test-gitlab-cli-arm64 test-terraform-ls-arm64 test-agentcore-arm64 test-aws-sam-cli-arm64

test-claude-code:
	devcontainer features test -f claude-code --base-image {{DEBIAN}} -p .
	devcontainer features test -f claude-code --base-image {{ALPINE}} -p .

test-just:
	devcontainer features test -f just --base-image {{DEBIAN}} -p .
	devcontainer features test -f just --base-image {{ALPINE}} -p .

test-kiro-cli:
	devcontainer features test -f kiro-cli --base-image {{DEBIAN}} -p .

test-nvidia-container-toolkit:
	devcontainer features test -f nvidia-container-toolkit --base-image {{DEBIAN}} -p .

test-act:
	devcontainer features test -f act --base-image {{DEBIAN}} -p .
	devcontainer features test -f act --base-image {{ALPINE}} -p .

test-gitlab-ci-local:
	devcontainer features test -f gitlab-ci-local --base-image {{DEBIAN}} -p .
	devcontainer features test -f gitlab-ci-local --base-image {{ALPINE}} -p .

test-prek:
	devcontainer features test -f prek --base-image {{DEBIAN}} -p .
	devcontainer features test -f prek --base-image {{ALPINE}} -p .

test-bash-language-server:
	devcontainer features test -f bash-language-server --base-image {{DEBIAN}} -p .
	devcontainer features test -f bash-language-server --base-image {{ALPINE}} -p .

test-gitlab-cli:
	devcontainer features test -f gitlab-cli --base-image {{DEBIAN}} -p .
	devcontainer features test -f gitlab-cli --base-image {{ALPINE}} -p .

test-terraform-ls:
	devcontainer features test -f terraform-ls --base-image {{DEBIAN}} -p .
	devcontainer features test -f terraform-ls --base-image {{ALPINE}} -p .

test-agentcore:
	devcontainer features test -f agentcore --base-image {{DEBIAN}} -p .
	devcontainer features test -f agentcore --base-image {{ALPINE}} -p .

test-aws-sam-cli:
	devcontainer features test -f aws-sam-cli --base-image {{DEBIAN}} -p .

_build-arm64 feature base:
    #!/usr/bin/env bash
    set -euo pipefail
    tag="devcontainer-feature-arm64/{{feature}}:$(echo '{{base}}' | tr ':/' '-')"
    docker buildx build \
        --platform linux/arm64 \
        --build-arg BASE_IMAGE={{base}} \
        --build-context feature=./src/{{feature}} \
        --build-context tests=./test/{{feature}} \
        --build-context testlib=./test \
        -t "$tag" \
        --load \
        -f test/Dockerfile.arm64 \
        .

_run-arm64 feature base:
    #!/usr/bin/env bash
    set -euo pipefail
    tag="devcontainer-feature-arm64/{{feature}}:$(echo '{{base}}' | tr ':/' '-')"
    docker run --rm --platform linux/arm64 "$tag" bash -c "cd /tmp/tests && bash test.sh"

test-claude-code-arm64:
    just _build-arm64 claude-code {{DEBIAN}}
    just _run-arm64 claude-code {{DEBIAN}}
    just _build-arm64 claude-code {{ALPINE}}
    just _run-arm64 claude-code {{ALPINE}}

test-just-arm64:
    just _build-arm64 just {{DEBIAN}}
    just _run-arm64 just {{DEBIAN}}
    just _build-arm64 just {{ALPINE}}
    just _run-arm64 just {{ALPINE}}

test-kiro-cli-arm64:
    just _build-arm64 kiro-cli {{DEBIAN}}
    just _run-arm64 kiro-cli {{DEBIAN}}

test-nvidia-container-toolkit-arm64:
    just _build-arm64 nvidia-container-toolkit {{DEBIAN}}
    just _run-arm64 nvidia-container-toolkit {{DEBIAN}}

test-act-arm64:
    just _build-arm64 act {{DEBIAN}}
    just _run-arm64 act {{DEBIAN}}
    just _build-arm64 act {{ALPINE}}
    just _run-arm64 act {{ALPINE}}

test-gitlab-ci-local-arm64:
    just _build-arm64 gitlab-ci-local {{DEBIAN}}
    just _run-arm64 gitlab-ci-local {{DEBIAN}}
    just _build-arm64 gitlab-ci-local {{ALPINE}}
    just _run-arm64 gitlab-ci-local {{ALPINE}}

test-prek-arm64:
    just _build-arm64 prek {{DEBIAN}}
    just _run-arm64 prek {{DEBIAN}}
    just _build-arm64 prek {{ALPINE}}
    just _run-arm64 prek {{ALPINE}}

test-bash-language-server-arm64:
    just _build-arm64 bash-language-server {{DEBIAN}}
    just _run-arm64 bash-language-server {{DEBIAN}}
    just _build-arm64 bash-language-server {{ALPINE}}
    just _run-arm64 bash-language-server {{ALPINE}}

test-gitlab-cli-arm64:
    just _build-arm64 gitlab-cli {{DEBIAN}}
    just _run-arm64 gitlab-cli {{DEBIAN}}
    just _build-arm64 gitlab-cli {{ALPINE}}
    just _run-arm64 gitlab-cli {{ALPINE}}

test-terraform-ls-arm64:
    just _build-arm64 terraform-ls {{DEBIAN}}
    just _run-arm64 terraform-ls {{DEBIAN}}
    just _build-arm64 terraform-ls {{ALPINE}}
    just _run-arm64 terraform-ls {{ALPINE}}

test-agentcore-arm64:
    just _build-arm64 agentcore {{DEBIAN}}
    just _run-arm64 agentcore {{DEBIAN}}
    just _build-arm64 agentcore {{ALPINE}}
    just _run-arm64 agentcore {{ALPINE}}

test-aws-sam-cli-arm64:
    just _build-arm64 aws-sam-cli {{DEBIAN}}
    just _run-arm64 aws-sam-cli {{DEBIAN}}

generate-docs:
	devcontainer features generate-docs -p src -n {{REPO}}

ACT_OPTS := '--container-options "-v /tmp:/tmp" --concurrent-jobs 4'

act-ci:
	act {{ACT_OPTS}} -W .github/workflows/ci.yml

act-validate:
	act pull_request {{ACT_OPTS}} -W .github/workflows/validate.yml

act-dry:
	act -n {{ACT_OPTS}} -W .github/workflows/ci.yml
	act pull_request -n {{ACT_OPTS}} -W .github/workflows/validate.yml

act-all: act-ci act-validate
